document.writeln('<header>');
document.writeln('<nav class="header-nav">');
document.writeln('<a href="../">EN <i class="fa-solid fa-globe"></i></a>');
document.writeln('<a href="#services">الخدمات</a>');
document.writeln('<a href="#contact">التواصل</a>');
document.writeln('<a href="blogs.html">مدونات</a>');
document.writeln('</nav>');
document.writeln('<a href="../ar/" class="icon-link">');
document.writeln('<p>استوديوهات بيرب هاوك</p>');
document.writeln('<img src="../img/logo-no-bg.png" class="header-icon" alt="logo">');
document.writeln('</a>');
document.writeln('</header>');