document.writeln('<header>');
document.writeln('<nav class="header-nav">');
document.writeln('<a href="../">EN <i class="fa-solid fa-globe"></i></a>');
document.writeln('<a href="#services">الخدمات</a>');
document.writeln('<a href="#contact">التواصل</a>');
document.writeln('</nav>');
document.writeln('<nav class="header-nav">');
document.writeln('<a href="#">تكنولوجيا</a>');
document.writeln('<a href="#">تقنية</a>');
document.writeln('<a href="#">شروحات</a>');
document.writeln('<a href="#">تعليم</a>');
document.writeln('<a href="#">عنا</a>');
document.writeln('<a href="#">مراجعات</a>');
document.writeln('<a href="#">انظمة تشغيل</a>');
document.writeln('</nav>');
document.writeln('<a href="#" class="icon-link">');
document.writeln('<p>استوديوهات بيرب هاوك</p>');
document.writeln('<img src="../img/logo-no-bg.png" class="header-icon" alt="logo">');
document.writeln('</a>');
document.writeln('</header>');